version: "3"

services:
  3x-ui:
    image: 'ghcr.io/mhsanaei/3x-ui:latest'
    container_name: 3x-ui
    hostname: vpn.automateme.ru  # Изменено: убран https://
    volumes:
      - '/home/user/3x-ui/db:/etc/x-ui/'
      - '/home/user/3x-ui/cert:/root/cert/'
    environment:
      XRAY_VMESS_AEAD_FORCED: 'false'
    tty: true
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    external: true
